version: '3.3'
services:
  db:
    image: mysql:8.0
    container_name: mysql-v1
    #restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '${MYSQL_EXPOSE_PORT}:${MYSQL_CONTAINER_PORT}'
    expose:
      - ${MYSQL_EXPOSE_PORT}

    volumes:
      - my-db:/var/lib/mysql
    networks:
      - task-network
# Names our volume
volumes:
  my-db:

networks:
  task-network: