version: '3.3'
services:
  db:
    image: mysql:8.0
    #restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '${EXPOSE_PORT}:${CONTAINER_PORT}'
    expose:
      # Opens port 3306 on the container
      - ${EXPOSE_PORT}
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - task-network
# Names our volume
volumes:
  my-db:

networks:
  task-network: