version: '3.3'
services:
  db:
    image: mysql:8.0
    container_name: mysql-v1
    #restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '${MYSQL_EXPOSE_PORT}:${MYSQL_CONTAINER_PORT}'
    expose:
      - ${MYSQL_EXPOSE_PORT}

    volumes:
      - my-db:/var/lib/mysql
    networks:
      - my-network

  #--------------------------#
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:5
    container_name: phpmyadmin-v1
    #restart: always
    ports:
      - '${PHP_EXPOSE_PORT}:${PHP_CONTAINER_PORT}'
    environment:
      PMA_HOST: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    
    networks:
      - my-network

# Names our volume
volumes:
  my-db:
    bar:
    driver: local
    driver_opts:
      #default path: /var/lib/docker/volmues
      device: './db-volumes/'
      o: bind
  

networks:
  my-network: